# Generated by Django 2.0 on 2018-05-26 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutGuitar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('overview', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='guitar')),
            ],
        ),
    ]
